### ISSUE TITLE
Adding quotes by user through GitHub Actions

### ISSUE THREAD

**Issue by SpiderMath** [EFFLUX110/api#2]
I came by this repository recently, and noticed this in the README.md of the project
> - [ ] Feature to add quote by a user directly from website using GitHub actions/api. 

It's obviously possible, however, I would suggest using a proper database, since it would be easier to manage.
If you still would like to go with the database as a few .txt files, then one thing you could do would be to create a separate Route which would update the txt files on getting a request, and then commit these changes to GitHub.

**Comment by Mrinank-Bhowmick** [comment]
Actually I am structuring the codebase in a very simple way so that any person looking into the repository can directly add single/multiple quotes via .txt files , and for adding quotes from website/frontend i will surely add a route as you said which will update the txt files.
Thanks 👍
